### ISSUE TITLE
"Use existing configuration" upload option is missing

### ISSUE THREAD

**Issue by kr15uk** [TeamGloomy/configtool#25]
On original RRF config you have an option to upload existing configuration file, super useful when you set up and/or fine tune your settings for the machine.

By the looks of it it's missing on LPC/STM despite still having a comment "...or by loading an existing JSON template:"

Any plans to get that working?!

Ta

Kris

**Comment by iZz0s** [comment]
im waiting for that option, too :(

**Comment by Paintrain-Ger** [comment]
Hey,

i'm also looking for that function... Hopefully it get's implemented. Any chance for an official statement?

Thanks!

David

**Comment by woheedev** [comment]
Not sure why it's hidden as it seems to be working fine but you can enable import by entering this in console:

`document.querySelector("#app > form > div > input[type=file]").hidden=false`
