### ISSUE TITLE
marlin default configuration request for BTT octopus v1.1

### ISSUE THREAD

**Issue by josh1e** [TeamGloomy/configtool#47]
Hi, the Octopus V1.1 supports Marlin 2.0 but I haven't been able to find any BTT or BIQU default Marlin v2 configurations for it.

Can you please create one and ask the Marlin build team to add it to the list of supported configurations (for public mass uptake) and include a copy in the BTT GIT repo?

I have looked in /configurations/examples/ and /configurations/examples/BIQU but nothing :(

item: [https://www.bigtree-tech.com/products/bigtreetech-octopus-v1-0-2.html](url)
Marlin default config examples: [https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples](url)
  
thanks

**Comment by DonBower** [comment]
I would settle for the Configuration.h and Configuration_adv.h files in the examples somewhere.
